"""test

Revision ID: f52bef30c001
Revises: 4d10660798b7
Create Date: 2023-04-01 20:13:50.402515

"""


# revision identifiers, used by Alembic.
revision = "f52bef30c001"
down_revision = "4d10660798b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
