"""Add description and category to bots

Revision ID: 38f0bc56a565
Revises: 4d10660798b7
Create Date: 2023-04-02 19:57:38.835927

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "38f0bc56a565"
down_revision = "4d10660798b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bot_config",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_config", "description")
    # ### end Alembic commands ###
