FROM prefecthq/prefect:2-python3.10

WORKDIR /app

RUN python -m venv venv
ENV VIRTUAL_ENV=/app/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY . /app

RUN pip install -e ".[chromadb]"

EXPOSE 8000

CMD ["python",  "/app/examples/slackbot/community_bot.py"]