# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2023-03-25T20:24:15+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class StreetType(Enum):
    Street = "Street"
    Avenue = "Avenue"
    Boulevard = "Boulevard"


class Model(BaseModel):
    number: Optional[float] = None
    street_name: Optional[str] = None
    street_type: Optional[StreetType] = None
