FROM prefecthq/prefect:2-python3.10

WORKDIR /app

RUN python -m venv venv
ENV VIRTUAL_ENV=/app/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --no-cache-dir git+https://github.com/PrefectHQ/marvin.git@slackbot#egg=marvin[chromadb]

CMD ["marvin", "server", "start"]