name: ðŸž Report a bug
description: Errors and regression reports with reproducing test cases and/or stack traces.
labels: ["status:triage", "bug"]
body:
  - type: markdown
    attributes:
      value: >
        Bug reports are often **usage questions, not bugs**. 
        If you do not have a strong understanding of the interface you are reporting a bug for, 
        please head to the [Marvin docs](https://www.askmarvin.ai/) and then ask your question on [Discord](https://discord.gg/Kgw4HpcuYG). 
        You are likely to get a response faster and learn more about the feature you're working with. 
        If the issue is determined to be a bug, please open an issue here.
  
  - type: markdown
    attributes:
      value: >
        1. A **succinct description of the problem** - typically a line or two at most

        2. A **succinct code example which reproduces the problem**, otherwise known as a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example. We recognize that LLM responses vary.

        3. The **complete stack trace for errors - please avoid screenshots, and use text formatted with three backticks**

        4. Additional details that may help us reproduce your issue.
  
  - type: checkboxes
    id: checks
    attributes:
      label: First check
      description: Please confirm and check all the following options.
      options:
        - label: I added a descriptive title to this issue.
          required: true
        - label: I used the GitHub search to try to find a similar issue and didn't find one.
          required: true
        - label: I searched the Marvin documentation for this issue.
          required: true


  - type: textarea
    attributes:
      label: Bug summary
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction
      description: >
        Provide your [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example here. We recognize that LLM responses vary.
      placeholder: "# Insert code here"
      render: python3
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error
      description: >
        Provide the full exception traceback.
        If the message is a warning, run your program with the ``-Werror`` flag:   ``python -Werror my_flow.py``
      placeholder: "# Copy complete stack trace and error message here, including log output if applicable."
      render: python3
    validations:
      required: false

  - type: textarea
    attributes:
      label: Versions
      description: >
        Provide information about your Marvin version and environment. 
        The easiest way to retrieve all of the information is the `marvin version` command.
      placeholder: "# Copy output of the `marvin version` command here"
      render: Text
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Happy engineering!**"
