name: 🚀 Propose a feature enhancement
description: Propose a new feature or an enhancement to an existing feature.
labels: ["status:triage", "enhancement"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: First check
      description: Please confirm and check all the following options.
      options:
        - label: I added a descriptive title to this issue.
          required: true
        - label: I used the GitHub search to look for a similar issue and didn't find it.
          required: true
        - label: I searched the Marvin documentation for this feature.
          required: true
          

  - type: textarea
    attributes:
      label: Describe the current behavior
      description: A clear and concise description of what Marvin currently does.
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Describe the proposed behavior
      description: A clear and concise description of what new feature or behavior you would like to see.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Example Use
      description: Provide an example of how an end user could leverage the proposed functionality.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Provide additional context about the use case here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Happy engineering!**"