
 blank_issues_enabled: false
contact_links:
  - name: 📖 Read the documentation
    url: https://askmarvin.ai
    about: Please consult the documentation before opening any issues!
  - name: 🙋 Ask a question
    url: https://discord.gg/Kgw4HpcuYG
    about: Ask questions about how to use Marvin on our Discord server.