name: Dependabot Evaluation

on:
    pull_request:
        paths:
            - "cookbook/**/*"

jobs:
    evaluate_dependabot_pr:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install PyGithub marvin

            - name: Run Dependabot Evaluation
              run: python cookbook/dependabot_auto_evaluation_pr.py
              env:
                  GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
